### ISSUE TITLE
Data before 2017

### ISSUE THREAD

**Issue by completelyboofyblitzed** [bryankolano/gdelt_pipeline_google_cloud#1]
Hey! I was just curious if it can grab the data before the year of 2017, aka the GDELT v.1 database and how far behind if it does.

**Comment by bryankolano** [comment]
Hi!  Version 2 of the data goes back to February, 2015.  Here is the listing of each data file.  

http://data.gdeltproject.org/gdeltv2/masterfilelist.txt

Version 1 of GDELT goes back longer:  

http://data.gdeltproject.org/events/index.html 

In April 2013, they started doing the daily GDELT roll up.  It looks like before that, files don't exist for each day, but rather as a summary for each month_year.

**Comment by completelyboofyblitzed** [comment]
Thank you!
